## Write a Numpy program to compute the multiplication of two given matrixes

In [3]:
import numpy as np
m=np.array([1,2,3,4])
n=np.array([1,2,3,4])
n*m

array([ 1,  4,  9, 16])

## Write a NumPy program to compute the determinant of a given square array

In [6]:
a = np.array([[1, 0], [1, 2]])
np.linalg.det(a)

2.0

## Write a NumPy program to compute the cross product of two given vectors

In [7]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
np.cross(p,q)

array([ 2, -3])

## Write a NumPy program to compute the condition number of a given matrix

In [15]:
from numpy import linalg as ln
a = np.array([[1,2],[3,4]])
ln.cond(a)

14.933034373659268

## Write a NumPy program to compute the inverse of a given matrix

In [16]:
ln.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])